# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tsunami < Formula
  desc "HTTP load testing CLI tool"
  homepage "https://github.com/paniccaaa/tsunami"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/paniccaaa/tsunami/releases/download/v0.1.6/tsunami_0.1.6_darwin_amd64.tar.gz"
      sha256 "9a3edc0427ae48ccf68e2dbe70064a6763c366029febe78cecad2f1e30fcf553"

      define_method(:install) do
        bin.install "tsunami"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/paniccaaa/tsunami/releases/download/v0.1.6/tsunami_0.1.6_darwin_arm64.tar.gz"
      sha256 "d2f85c2fd347d2fb9a61431b64fca62f70620f268523e6718de93c1ba4f42c95"

      define_method(:install) do
        bin.install "tsunami"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/paniccaaa/tsunami/releases/download/v0.1.6/tsunami_0.1.6_linux_amd64.tar.gz"
      sha256 "e973ffca9f0b1c17df7bf8b1fa05ea23f5a5ff733f6ab5d1cc4dcd8d7b36801a"
      define_method(:install) do
        bin.install "tsunami"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/paniccaaa/tsunami/releases/download/v0.1.6/tsunami_0.1.6_linux_arm64.tar.gz"
      sha256 "0d31fb99b2092aa430876ec761fb10520e95a92671311340038d74c2a56d57eb"
      define_method(:install) do
        bin.install "tsunami"
      end
    end
  end

  test do
    system "#{bin}/tsunami", "--version"
  end
end
