# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tsunami < Formula
  desc "HTTP load testing CLI tool"
  homepage "https://github.com/paniccaaa/tsunami"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/paniccaaa/tsunami/releases/download/v0.1.5/tsunami_0.1.5_darwin_amd64.tar.gz"
      sha256 "e88b36ac004216ce2e7977241ed174ca63abb6780a0f934f5a684322d4f41da3"

      define_method(:install) do
        bin.install "tsunami"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/paniccaaa/tsunami/releases/download/v0.1.5/tsunami_0.1.5_darwin_arm64.tar.gz"
      sha256 "d4955a5c546b678e2b7c7a63708717602b83b38455854add86dc3bb91e756904"

      define_method(:install) do
        bin.install "tsunami"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/paniccaaa/tsunami/releases/download/v0.1.5/tsunami_0.1.5_linux_amd64.tar.gz"
      sha256 "888223a463671eeccd09f93d9cfe4c8c74d26f52a943d5905304d27482b2a838"
      define_method(:install) do
        bin.install "tsunami"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/paniccaaa/tsunami/releases/download/v0.1.5/tsunami_0.1.5_linux_arm64.tar.gz"
      sha256 "32f31f161aa77167e4b5546bc3d8fffed59f48ec03cb58bfabdfad552e18dbd3"
      define_method(:install) do
        bin.install "tsunami"
      end
    end
  end

  test do
    system "#{bin}/tsunami", "--version"
  end
end
