# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tsunami < Formula
  desc "HTTP load testing CLI tool"
  homepage "https://github.com/paniccaaa/tsunami"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/paniccaaa/tsunami/releases/download/v0.1.2/tsunami_0.1.2_darwin_amd64.tar.gz"
      sha256 "1ac580aa3ed01f9a101704ee103dcaea1e10cd53cab45a3563b00a898ca2b702"

      def install
        bin.install "tsunami"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/paniccaaa/tsunami/releases/download/v0.1.2/tsunami_0.1.2_darwin_arm64.tar.gz"
      sha256 "abdd03be631e80b0f0c1f7253182ddf6f0243ef668e74b0a034c9d035bc2cb29"

      def install
        bin.install "tsunami"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/paniccaaa/tsunami/releases/download/v0.1.2/tsunami_0.1.2_linux_amd64.tar.gz"
      sha256 "595b7b473ad293637999b63dcbecb4685bc9b7d5193dc0f621fedf496c8af5d9"
      def install
        bin.install "tsunami"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/paniccaaa/tsunami/releases/download/v0.1.2/tsunami_0.1.2_linux_arm64.tar.gz"
      sha256 "5d4381f809e328b65fa31d5ad63bbff9144ce9fda3f0b7643ca96ca3030fb106"
      def install
        bin.install "tsunami"
      end
    end
  end

  test do
    system "#{bin}/tsunami", "--version"
  end
end
